language: java


# activate profile no-integration-tests so test sources and their dependencies can be excluded from build
# (there is no jboss server installed on travis anyway)
# deactivate profile integration-tests (it is active by default)
script: mvn clean install -B -P no-integration-tests,-integration-tests

branches:
  only:
    - master
    - integration

jdk:
  - oraclejdk6
  - oraclejdk7
  - openjdk7

before_script:
  - mysql -e 'create database idpdbtest;'
  - mysql -uroot -e 'GRANT ALL PRIVILEGES ON idpdbtest.* TO idptest@localhost IDENTIFIED BY "idptest";'
  - mysql -e 'create database platodbtest;'
  - mysql -uroot -e 'GRANT ALL PRIVILEGES ON platodbtest.* TO platotest@localhost IDENTIFIED BY "platotest";'
