language: java

# install: mvn install -DskipTests=true -B -P no-integration-tests,-integration-tests

script: mvn clean install -B -P no-integration-tests,-integration-tests

branches:
  only:
    - master
    - integration

jdk:
  - oraclejdk6
  - oraclejdk7
  - openjdk7

before_script:
  - mysql -e 'create database idpdbtest;'
  - mysql -uroot -e 'GRANT ALL PRIVILEGES ON idpdbtest.* TO idptest@localhost IDENTIFIED BY "idptest";'
  - mysql -e 'create database platodbtest;'
  - mysql -uroot -e 'GRANT ALL PRIVILEGES ON platodbtest.* TO platotest@localhost IDENTIFIED BY "platotest";'
